### ISSUE TITLE
Could not find com.salesforce.service:chat-ui:4.3.4.

### ISSUE THREAD

**Issue by fedeinfe** [navy774989/react-native-salesforce-chat-sdk#3]
Hi everyone, when I try to build the app with this library installed, it crashes because it can reach https://s3.amazonaws.com/salesforcesos.com/android/maven/release to download maven dependences.

Any solution?

On iOS it works flawless

**Comment by navy774989** [comment]
@fedeinfe  i think if you follow the step from [salesforce official website](https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_install_sdk.htm), you will be able to download the sdk.
this library already cached the iOS sdk, but i can't cache android SDK. that way ios works

**Comment by fedeinfe** [comment]
my solution has been to add  this in build.grandle 
`    maven {
        url "https://salesforcesos.com/android/maven/release"
    }`
